site:
  title: Compedia
  url: https://kboom.github.io/Compedia/
  start_page: compedia::index.adoc
content:
  sources:
    - url: ./
      branches: HEAD
      start_paths:
        - Docs # https://docs.antora.org/antora/latest/playbook/content-source-start-paths/ can support globs
        - ./*/Docs
ui:
  supplemental_files: ./Docs/ui
  bundle:
    url: https://github.com/vshn/antora-ui-default/releases/download/2.1.0/ui-bundle.zip
asciidoc:
  attributes:
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
output:
  dir: .public
