version: '3.4'

services:
  identity:
    environment:
      - "ConnectionStrings__DefaultConnection=Server=identity-db;Database=IdentityDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Persistence:SeedData=true
    ports:
      - "5080:80"
      - "5443:443"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro