version: '3.9'

services:
  identity:
    image: ${DOCKER_REGISTRY-}compedia_identity
    depends_on:
    - identity-db
    build:
      context: .
      dockerfile: Identity\Dockerfile

  identity-db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Your_password123"
      - "ACCEPT_EULA=Y"

  search:
    image: ${DOCKER_REGISTRY-}compedia_search
    depends_on:
    - identity
    build:
      context: .
      dockerfile: Search\Dockerfile

  webapp:
    image: ${DOCKER_REGISTRY-}compedia_webapp
    build:
      context: .
      dockerfile: Webapp\Dockerfile