version: "3.9"

# For now it seems the problem is that we're using both localhost and internal domain names
# This is confusing. Try to make windows understand internal domain names of the containers so that the browser redirects in oauth work nice.
# Alternatively, expose ports and keep using localhost...
# https://gist.github.com/BretFisher/f1d1be2a8ab6df379018bcbf766e74a4
# https://www.supereasy.com/how-to-configure-nginx-as-a-https-reverse-proxy-easily/
# test this https://www.supereasy.com/how-to-configure-nginx-as-a-https-reverse-proxy-easily/
services:
  identity:
    environment:
      - "ConnectionStrings__DefaultConnection=Server=identity-db;Database=IdentityDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
      - "ConnectionStrings__ConfigurationDbConnection=Server=identity-db;Database=ConfigurationDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=identity-db;Database=PersistedGrantDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/identity.compedia.local.pfx
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:9443
      - Persistence:SeedData=true
    ports:
      - "5443:9443"
    volumes:
      - ./Cluster/local/trust.root.cert.sh/:/https/trust.sh:ro
      - ./Cluster/local/Certs/root-cert.cer:/https/root-cert.cer:ro
      - ./Cluster/local/Certs/identity.compedia.local.pfx:/https/identity.compedia.local.pfx:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    entrypoint:
      - /https/trust.sh
  identity-db:
    ports:
      - "11433:1433"
  search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/search.compedia.local.pfx
    ports:
      - "6443:443"
    volumes:
      - ./Cluster/local/trust.root.cert.sh/:/https/trust.sh:ro
      - ./Cluster/local/Certs/root-cert.cer:/https/root-cert.cer:ro
      - ./Cluster/local/Certs/search.compedia.local.pfx:/https/search.compedia.local.pfx:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    entrypoint:
      - /https/trust.sh
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/web-app.compedia.local.pfx
      - OidcSettings__AuthorityServerUrl=https://identity.compedia.local:9443
    volumes:
      - ./Cluster/local/trust.root.cert.sh/:/https/trust.sh:ro
      - ./Cluster/local/Certs/root-cert.cer:/https/root-cert.cer:ro
      - ./Cluster/local/Certs/web-app.compedia.local.pfx:/https/web-app.compedia.local.pfx:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    ports:
      - "4433:443"
    entrypoint:
      - /https/trust.sh
