version: "3.9"

services:
  identity:
    init: true
    entrypoint: docker-entrypoint
    command: tail -f /dev/null
    volumes:
      - ./docker.entrypoint.sh/:/usr/local/bin/docker-entrypoint/:ro
  search:
    init: true
    entrypoint: docker-entrypoint
    command: tail -f /dev/null
    volumes:
      - ./docker.entrypoint.sh/:/usr/local/bin/docker-entrypoint/:ro
  webapp:
    init: true
    entrypoint: docker-entrypoint
    command: tail -f /dev/null
    volumes:
      - ./docker.entrypoint.sh/:/usr/local/bin/docker-entrypoint/:ro
