version: "3.9"

services:
  identity:
    environment:
      - "ConnectionStrings__DefaultConnection=Server=identity-db;Database=IdentityDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
      - "ConnectionStrings__ConfigurationDbConnection=Server=identity-db;Database=ConfigurationDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=identity-db;Database=PersistedGrantDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp-identity.pfx
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - Persistence:SeedData=true
    ports:
      - "5443:443"
    volumes:
      - ./Certs:/https/
      - type: bind
        source: ./Certs/aspnetapp-root-cert.cer
        target: /https-root/aspnetapp-root-cert.cer
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    entrypoint:
      - /https/TrustRootCert.sh
  search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp-search.pfx
    ports:
      - "6443:443"
    volumes:
      - ./Certs:/https/
      - type: bind
        source: ./Certs/aspnetapp-root-cert.cer
        target: /https-root/aspnetapp-root-cert.cer
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    entrypoint:
      - /https/TrustRootCert.sh
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp-web-app.pfx
      - OidcSettings__AuthorityServerUrl=https://identity
    volumes:
      - ./Certs:/https/
      - type: bind
        source: ./Certs/aspnetapp-root-cert.cer
        target: /https-root/aspnetapp-root-cert.cer
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    ports:
      - "4433:443"
    entrypoint:
      - /https/TrustRootCert.sh
