version: '3.9'

services:
  identity:
    image: ${DOCKER_REGISTRY-}compedia_identity
    build:
      context: .
      dockerfile: Identity\Dockerfile
    environment:
      "ConnectionStrings__DefaultConnection": Server=db;Database=IdentityDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true
  identity-db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Pass123!"
      - "ACCEPT_EULA=Y"